server.port=${PORT:8081}

kafka.bootstrap-servers=${BOOTSTRAP_SERVER_URL:localhost:9092}

management.endpoints.access.default=none
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.access=read_only
